#!/bin/sh

print_green() {
    echo "\033[0;32m$1\033[0m"
}

print_blue() {
    echo "\033[0;34m$1\033[0m"
}

print_yellow() {
    echo "\033[1;33m$1\033[0m"
}

print_grey() {
    echo "\033[1;30m$1\033[0m"
}

print_cyan() {
    echo "\033[1;36m$1\033[0m"
}

lint_commit_message() {
    print_blue "CHECKING COMMIT MESSAGE"
    print_grey "$1"
    npx --no -- commitlint --edit $1
}

lint_commit_message $1
