#!/bin/sh

print_green() {
    echo "\033[0;32m$1\033[0m"
}

print_blue() {
    echo "\033[0;34m$1\033[0m"
}

print_yellow() {
    echo "\033[1;33m$1\033[0m"
}

print_grey() {
    echo "\033[1;30m$1\033[0m"
}

print_cyan() {
    echo "\033[1;36m$1\033[0m"
}

warning() {
    print_yellow "PLEASE CHECK LINT AND TEST RESULT IN CI!"
}

warning
